export const RENDER_EDIT_USER = 'RENDER_EDIT_USER';
export const RENDER_CREATE_USER = 'RENDER_CREATE_USER';
export const RENDER_LIST_USER = 'RENDER_LIST_USER';
export const RENDER_HOME = 'RENDER_HOME';
export const RENDER_ROLE_PERMISSION = 'RENDER_ROLE_PERMISSION';
export const RENDER_SETTING = 'RENDER_SETTING';
export const RENDER_USER_DETAIL = 'RENDER_USER_DETAIL';

export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const APPROVE_USER = 'APPROVE_USER';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
